### ISSUE TITLE
3D/Effects tab missing

### ISSUE THREAD

**Issue by ThreeDeeJay** [sam-truscott/wumpusopenal#3]
I noticed a screenshot online that has [this tab](https://www.softpedia.com/get/Multimedia/Audio/Audio-Plugins/Wumpus-OpenAL-Output.shtml#sgal_1)
![image](https://user-images.githubusercontent.com/71472458/209424716-a5e2480e-6322-45a5-98a3-fac537c9d564.png)
But it's missing on my end.
![winamp_WA17KnTM80](https://user-images.githubusercontent.com/71472458/209424770-29f93d15-0ccd-48f3-9b71-8e9dc36ef857.png)

**Comment by sam-truscott** [comment]
Heya,

I removed it here: https://github.com/sam-truscott/wumpusopenal/commit/448c723e58f447f9797fd3adb9b2b24d362440e1

As noted, it was due to Creative taking over the SDK and it getting quite broken.

I'll see how easy it is to reverse and re-integrate.

**Comment by ThreeDeeJay** [comment]
ahh that explains it, I see it now with an older version, though just as noted somewhere, the left and right ear streams are desynced.
If the original OpenAL API is problematic, you might wanna check out the open-source fork: https://github.com/kcat/openal-soft

**Comment by sam-truscott** [comment]
Yeah my concern with the software implementations of OpenAL has always been, does this make the original aim of the project defunct (i.e. bypass Windows Vistas - at the time - software audio mixer because Direct Sound had gone).

This is still true today; and this project is largely no longer relevant; there's newer and better API's such as WASAPI (with exclusive access) or ASIO - both of which achieve the original aims. I believe Winamp (or WACUP if you've gone that way) has plugins for these already.

I guess positional audio might fall outside of the above; that might be handled by ASIO or the various WASAPI driver implementations.

**Comment by ThreeDeeJay** [comment]
Yeah, from what I've seen, OpenAL Soft has grown into much more than working around HAL/DirectSound(3D) deprecation.
And on Windows, it uses WASAPI (shared) for output by default, but [it's possible to make it use WASAPI exclusive with some modifications](https://github.com/ThreeDeeJay/openal-soft/releases/tag/1.22.2-WASAPI-exclusive).
We can use ASIO for multichannel output into [Crystal Mixer](https://crystal-mixer.sourceforge.net/) which can spatialize/virtualize surround and add EAX so I guess I can use those, I was just curious about doing it directly within Winamp because CM can be a bit tedious to set up.
So I'll just go ahead and close this issue and watch this repo in case 3D/effects are brought back 👍
